# ORDERS DATA EXPLORATION

In [0]:
# Import essential libraries for data handling and visualization
import pandas as pd
import matplotlib.pyplot as plt

In [0]:
# Load order data from CSV into a DataFrame
# Preview the first five rows to verify successful loading
df_orders = pd.read_csv('/Volumes/retail_catalog/default/raw_data/Orders.csv')
df_orders.head()

                           order_id  ... order_estimated_delivery_date
0  e481f51cbdc54678b7cc49136f2d6af7  ...           2017-10-18 00:00:00
1  53cdb2fc8bc7dce0b6741e2150273451  ...           2018-08-13 00:00:00
2  47770eb9100c2d0c44946d9cf07ec65d  ...           2018-09-04 00:00:00
3  949d5b44dbf5de918fe9c16f97b45f8a  ...           2017-12-15 00:00:00
4  ad21c59c0840e6cb83a9ceb5573f8159  ...           2018-02-26 00:00:00

[5 rows x 8 columns]

In [0]:
# Display the number of rows and columns in the DataFrame
df_orders.shape

(99441, 8)

In [0]:
# Show information on columns, data types, and missing values
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [0]:
# Display summary statistics for numeric columns
df_orders.describe().T

                               count  ...   freq
order_id                       99441  ...      1
customer_id                    99441  ...      1
order_status                   99441  ...  96478
order_purchase_timestamp       99441  ...      3
order_approved_at              99281  ...      9
order_delivered_carrier_date   97658  ...     47
order_delivered_customer_date  96476  ...      3
order_estimated_delivery_date  99441  ...    522

[8 rows x 4 columns]

In [0]:
# Count missing (null) values in each column
df_orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [0]:
# Count unique values per column to evaluate categorical diversity
df_orders.nunique()

order_id                         99441
customer_id                      99441
order_status                         8
order_purchase_timestamp         98875
order_approved_at                90733
order_delivered_carrier_date     81018
order_delivered_customer_date    95664
order_estimated_delivery_date      459
dtype: int64

In [0]:
# Convert string columns to datetime format for temporal analysis
cols_to_convert = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

df_orders[cols_to_convert] = df_orders[cols_to_convert].apply(
    lambda col: pd.to_datetime(col, dayfirst=True, errors='coerce')
)

/home/spark-ceb5d5c9-77bc-44f0-a507-a6/.ipykernel/2714/command-6085097560493355-2705580636:11: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  lambda col: pd.to_datetime(col, dayfirst=True, errors='coerce')

In [0]:
# Check column data types after datetime conversion to confirm transformation
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       39631 non-null  datetime64[ns]
 4   order_approved_at              39648 non-null  datetime64[ns]
 5   order_delivered_carrier_date   37332 non-null  datetime64[ns]
 6   order_delivered_customer_date  36354 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [0]:
# Find and print the minimum and maximum order purchase dates
min_purchase_date = df_orders['order_purchase_timestamp'].min()
max_purchase_date = df_orders['order_purchase_timestamp'].max()

print('Order Purchase Date Range: {} to {}'.format(min_purchase_date, max_purchase_date))

Order Purchase Date Range: 2016-02-10 22:07:52 to 2018-12-09 15:32:16

In [0]:
# Find and print the minimum and maximum order approval dates
min_approval_date = df_orders['order_approved_at'].min()
max_approval_date = df_orders['order_approved_at'].max()

print('Order Approval Date Range: {} to {}'.format(min_approval_date, max_approval_date))

Order Approval Date Range: 2016-04-10 09:43:32 to 2018-12-08 23:55:13

In [0]:
# Find and print the minimum and maximum order delivery carrier dates
min_delivery_date = df_orders['order_delivered_carrier_date'].min()
max_delivery_date = df_orders['order_delivered_carrier_date'].max()
print('Order Delivery Carrier Date Range: {} to {}'.format(min_delivery_date, max_delivery_date))

Order Delivery Carrier Date Range: 2016-01-11 07:13:36 to 2018-12-07 19:46:00

In [0]:
# Find and print the minimum and maximum order delivery customer dates
min_delivery_date = df_orders['order_delivered_customer_date'].min()
max_delivery_date = df_orders['order_delivered_customer_date'].max()
print('Order Delivery Customer Date Range: {} to {}'.format(min_delivery_date, max_delivery_date))

Order Delivery Customer Date Range: 2016-01-11 10:28:49 to 2018-12-09 20:15:38

In [0]:
# Display unique values for order status to explore different order lifecycle stages
df_orders['order_status'].unique()

array(['delivered', 'invoiced', 'shipped', 'processing', 'unavailable',
       'canceled', 'created', 'approved'], dtype=object)